### ISSUE TITLE
Application namespacing

### ISSUE THREAD

**Issue by jrf0110** [goodybag/escher#2]
So, earlier I put all of the pieces of rad into a single variable. And suddenly things got not quite as pretty. It's all fine and dandy, but there's some really separate functionality in there and it doesn't look like it belongs under a single namespace.

For instance, we've got rad.utils which is the facade for backbone and jquery and underscore. And then we have rad.apps which contains all of the registered applications. They really have nothing to do with each other.

Since we're using require.js, we don't really HAVE to stick to one namespace for everything. So my thinking is rad should be broken up into different modules and it should STAY in different modules even in production.

Those modules being:
- utils
- App
- Suite
- comm/event
- apps-handler

Aura actually does the same thing. There's no aura namespace, you just include the sandbox and core and what not.

**Comment by nijikokun** [comment]
If we go this route should we keep a name-case convention such as modules namespaces first characters are upper-case only? Also, does going this route have any downfalls or drastic changes?

**Comment by jrf0110** [comment]
No drastic changes since it started off that way.

The name-case convention I was using was if its it's a constructor it's uppercase if not it's not.
